//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaOsvaldo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Nullable<int> idFactura { get; set; }
        public System.DateTime fecha { get; set; }
        public int idTipoPago { get; set; }
        public int idCliente { get; set; }
        public int idSucursal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
